#!/usr/bin/python3
""" Square CLASS MODULE """
from models.rectangle import Rectangle


class Square(Rectangle):
    """ Square class """
    def __init__(self, size, x=0, y=0, id=None):
        """ Initialization function """
        super().__init__(size, size, x, y, id)

    def __str__(self):
        """ str function """
        return ("[Square] ({}) {}/{} - {}".
                format(self.id, self.x, self.y, self.height))

    @property
    def size(self):
        """ Get size function """
        return (self.height)

    @size.setter
    def size(self, v):
        """ Set size function """
        self.height = v
        self.width = v
